[package]
name = "yeastsimulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.'*']
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
glam = "0.20.1"
macroquad = "0.3"
oorandom = "11.1.3"
rstar = "0.9.2"